services:
  homeasswol:
    image: darkaxi0m/homeass-wol:main
    volumes:
      - ./servers.yaml:/app/servers.yaml:ro
    environment:
      MQTT_BROKER: tcp://10.1.1.36:1883
      CONFIG_FILE: servers.yaml
    network_mode: host
    cap_add:
      - NET_RAW
