package homeassistant

// BinarySensorClass represents the Home Assistant binary sensor device class type.
type BinarySensorClass string

// Binary sensor device class constants.
const (
	BinarySensorClassNone            BinarySensorClass = ""
	BinarySensorClassBattery         BinarySensorClass = "battery"
	BinarySensorClassBatteryCharging BinarySensorClass = "battery_charging"
	BinarySensorClassCarbonMonoxide  BinarySensorClass = "carbon_monoxide"
	BinarySensorClassCold            BinarySensorClass = "cold"
	BinarySensorClassConnectivity    BinarySensorClass = "connectivity"
	BinarySensorClassDoor            BinarySensorClass = "door"
	BinarySensorClassGarageDoor      BinarySensorClass = "garage_door"
	BinarySensorClassGas             BinarySensorClass = "gas"
	BinarySensorClassHeat            BinarySensorClass = "heat"
	BinarySensorClassLight           BinarySensorClass = "light"
	BinarySensorClassLock            BinarySensorClass = "lock"
	BinarySensorClassMoisture        BinarySensorClass = "moisture"
	BinarySensorClassMotion          BinarySensorClass = "motion"
	BinarySensorClassMoving          BinarySensorClass = "moving"
	BinarySensorClassOccupancy       BinarySensorClass = "occupancy"
	BinarySensorClassOpening         BinarySensorClass = "opening"
	BinarySensorClassPlug            BinarySensorClass = "plug"
	BinarySensorClassPower           BinarySensorClass = "power"
	BinarySensorClassPresence        BinarySensorClass = "presence"
	BinarySensorClassProblem         BinarySensorClass = "problem"
	BinarySensorClassRunning         BinarySensorClass = "running"
	BinarySensorClassSafety          BinarySensorClass = "safety"
	BinarySensorClassSmoke           BinarySensorClass = "smoke"
	BinarySensorClassSound           BinarySensorClass = "sound"
	BinarySensorClassTamper          BinarySensorClass = "tamper"
	BinarySensorClassUpdate          BinarySensorClass = "update"
	BinarySensorClassVibration       BinarySensorClass = "vibration"
	BinarySensorClassWindow          BinarySensorClass = "window"
)

// SensorClass represents the Home Assistant sensor device class type.
type SensorClass string

// Sensor device class constants.
const (
	SensorClassNone                          SensorClass = ""
	SensorClassApparentPower                 SensorClass = "apparent_power"
	SensorClassAQI                           SensorClass = "aqi"
	SensorClassArea                          SensorClass = "area"
	SensorClassAtmosphericPressure           SensorClass = "atmospheric_pressure"
	SensorClassBattery                       SensorClass = "battery"
	SensorClassBloodGlucoseConcentration     SensorClass = "blood_glucose_concentration"
	SensorClassCarbonDioxide                 SensorClass = "carbon_dioxide"
	SensorClassCarbonMonoxide                SensorClass = "carbon_monoxide"
	SensorClassCurrent                       SensorClass = "current"
	SensorClassDataRate                      SensorClass = "data_rate"
	SensorClassDataSize                      SensorClass = "data_size"
	SensorClassDate                          SensorClass = "date"
	SensorClassDistance                      SensorClass = "distance"
	SensorClassDuration                      SensorClass = "duration"
	SensorClassEnergy                        SensorClass = "energy"
	SensorClassEnergyDistance                SensorClass = "energy_distance"
	SensorClassEnergyStorage                 SensorClass = "energy_storage"
	SensorClassEnum                          SensorClass = "enum"
	SensorClassFrequency                     SensorClass = "frequency"
	SensorClassGas                           SensorClass = "gas"
	SensorClassHumidity                      SensorClass = "humidity"
	SensorClassIlluminance                   SensorClass = "illuminance"
	SensorClassIrradiance                    SensorClass = "irradiance"
	SensorClassMoisture                      SensorClass = "moisture"
	SensorClassMonetary                      SensorClass = "monetary"
	SensorClassNitrogenDioxide               SensorClass = "nitrogen_dioxide"
	SensorClassNitrogenMonoxide              SensorClass = "nitrogen_monoxide"
	SensorClassNitrousOxide                  SensorClass = "nitrous_oxide"
	SensorClassOzone                         SensorClass = "ozone"
	SensorClassPH                            SensorClass = "ph"
	SensorClassPM1                           SensorClass = "pm1"
	SensorClassPM25                          SensorClass = "pm25"
	SensorClassPM10                          SensorClass = "pm10"
	SensorClassPowerFactor                   SensorClass = "power_factor"
	SensorClassPower                         SensorClass = "power"
	SensorClassPrecipitation                 SensorClass = "precipitation"
	SensorClassPrecipitationIntensity        SensorClass = "precipitation_intensity"
	SensorClassPressure                      SensorClass = "pressure"
	SensorClassReactivePower                 SensorClass = "reactive_power"
	SensorClassSignalStrength                SensorClass = "signal_strength"
	SensorClassSoundPressure                 SensorClass = "sound_pressure"
	SensorClassSpeed                         SensorClass = "speed"
	SensorClassSulphurDioxide                SensorClass = "sulphur_dioxide"
	SensorClassTemperature                   SensorClass = "temperature"
	SensorClassTimestamp                     SensorClass = "timestamp"
	SensorClassVolatileOrganicCompounds      SensorClass = "volatile_organic_compounds"
	SensorClassVolatileOrganicCompoundsParts SensorClass = "volatile_organic_compounds_parts"
	SensorClassVoltage                       SensorClass = "voltage"
	SensorClassVolume                        SensorClass = "volume"
	SensorClassVolumeFlowRate                SensorClass = "volume_flow_rate"
	SensorClassVolumeStorage                 SensorClass = "volume_storage"
	SensorClassWater                         SensorClass = "water"
	SensorClassWeight                        SensorClass = "weight"
	SensorClassWindDirection                 SensorClass = "wind_direction"
	SensorClassWindSpeed                     SensorClass = "wind_speed"
)
