import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

import Image from 'next/image'
import logo from './logo.png'

export const metadata: Metadata = {
  title: "HomeAss WOL",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}; 

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <main
            className="flex min-h-screen flex-col items-center justify-center
               bg-slate-500
              "
          >
       
            <h1 className="flex mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
                 <Image 
      src={logo}
      height={60}
      alt="logo"
      className="mr-2"
    />
              HomeAss WOL{" "}
            </h1>

            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
